language: node_js
sudo: false

node_js:
  - "4"
  - "6"

env:
  - KAFKA_HOME=../kafka KAFKA_VERSION=0.9.0.1 CXX=g++-4.8

before_install:
- npm run install-kafka
- npm run start-kafka

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

script: npm run coverage && (npm run coveralls || exit 0)

after_script: sh test/utils/start_kafka.sh kill