num_workers: 0
logging:
  name: changeprop
  level: info
services:
  - name: changeprop
    module: hyperswitch
    conf:
      port: 7272
      spec:
        x-sub-request-filters:
          - type: default
            name: http
            options:
              allow:
                - pattern: /^https?:\/\//
        title: The Change Propagation root
        paths:
          /sys/purge:
            x-modules:
              - path: sys/purge.js
                options:
                  host: 127.0.0.1
                  port: 4321
          /sys/links:
            x-modules:
              - path: sys/backlinks.js
                options:
                  templates:
                    mw_api:
                        uri: 'https://{{message.meta.domain}}/w/api.php'
                        headers:
                          host: '{{message.meta.domain}}'
          /sys/queue:
            x-modules:
              - path: sys/kafka.js
                options:
                  uri: 127.0.0.1:2181
                  dc_name: test_dc
                  templates:

                    summary_rerender:
                      topic: resource_change
                      retry_limit: 2
                      retry_delay: 500
                      retry_on:
                        status:
                          - '5xx'
                      match:
                        meta:
                          uri: '/^(https?):\/\/[^\/]+\/api\/rest_v1\/page\/html\/([^/]+)$/'
                        tags:
                          - restbase
                      match_not:
                        meta:
                          domain: '/wiktionary.org$/'
                      exec:
                        method: get
                        # Don't encode title since it should be already encoded
                        uri: '{{match.meta.uri[1]}}://{{message.meta.domain}}/api/rest_v1/page/summary/{{match.meta.uri[2]}}'
                        query:
                          redirect: false
                        headers:
                          cache-control: no-cache

                    definition_rerender:
                      topic: resource_change
                      retry_limit: 2
                      retry_delay: 500
                      retry_on:
                        status:
                          - '5xx'
                      match:
                        meta:
                          # These URIs are coming from RESTBase, so we know that article titles will be normalized
                          # and main namespace articles will not have : (uri-encoded, so %3a or %3A)
                          uri: '/^(https?):\/\/[^\/]+\/api\/rest_v1\/page\/html\/((?:(?!%3a|%3A).)+)$/'
                          domain: '/^en.wiktionary.org$/'
                        tags:
                          - restbase
                      exec:
                        method: get
                        # Don't encode title since it should be already encoded
                        uri: '{{match.meta.uri[1]}}://{{message.meta.domain}}/api/rest_v1/page/definition/{{match.meta.uri[2]}}'
                        query:
                          redirect: false
                        headers:
                          cache-control: no-cache

                    mobile_rerender:
                      topic: resource_change
                      retry_limit: 2
                      retry_delay: 500
                      retry_on:
                        status:
                          - '5xx'
                      match:
                        meta:
                          uri: '/^(https?):\/\/[^\/]+\/api\/rest_v1\/page\/html\/([^/]+)$/'
                      exec:
                        method: get
                        uri: '{{match.meta.uri[1]}}://{{message.meta.domain}}/api/rest_v1/page/mobile-sections/{{match.meta.uri[2]}}'
                        query:
                          redirect: false
                        headers:
                          cache-control: no-cache

                    purge_varnish:
                      topic: resource_change
                      match:
                        meta:
                          uri: '/^https?:\/\/[^\/]+\/api\/rest_v1\/(.+)$/'
                        tags:
                          - restbase
                      exec:
                        method: post
                        uri: '/sys/purge/'
                        body:
                          - meta:
                              uri: '//{{message.meta.domain}}/api/rest_v1/{{match.meta.uri[1]}}'
