spec: &spec
  x-sub-request-filters:
    - type: default
      name: http
      options:
        allow:
          - pattern: /^https?:\/\//
            forward_headers:
              user-agent: true
  title: The Change Propagation root
  paths:
    /sys/dedupe:
      x-modules:
        - path: sys/deduplicator.js
          options:
            redis_prefix: CPJQ
            redis:
              host: '{env(REDIS_HOST)}'
              port: '{env(REDIS_PORT)}'
    /sys/queue:
      x-modules:
        - path: sys/kafka.js
          options:
            metadata_broker_list: '{env(KAFKA_BROKER_LIST)}'
            dc_name: eqiad
            startup_delay: 0
            concurrency: 250
            templates:
              job:
                topic: '/mediawiki\.job\..*'
                exec:
                  method: post
                  uri: '{env(MEDIAWIKI_URI)}/wiki/Special:RunSingleJob'
                  headers:
                    content-type: application/json
                    host: '{{message.meta.domain}}'
                  body: '{{globals.message}}'

num_workers: 0
logging:
  name: changeprop
  level: info
services:
  - name: changeprop
    module: hyperswitch
    conf:
      port: 7272
      user_agent: JobQueuePropInstance
      spec: *spec
